### ISSUE TITLE
nw_protocol_instance_access_flow_state [C15.1.1:2] Failed to find flow 105c1ddd8

### ISSUE THREAD

**Issue by joneswe** [oddbit/flutter_facebook_app_events#109]
Hey,
I have have Problem by sending logs to FB on iOS. By trying to send any log event (eg. logEvent(...)) nothing happens.
I only got a log which is saying:

nw_protocol_instance_access_flow_state [C15.1.1:2] Failed to find flow 105c1ddd8

## Expected Behavior
logging Events to FB

## Current Behavior
I don't receive any logs, because no logs are going out.
just getting 
nw_protocol_instance_access_flow_state [C15.1.1:2] Failed to find flow 105c1ddd8
in log

## Possible Solution
Maybe the fb sdk has to be updated?

## Steps to Reproduce (for bugs)
just doing the install/example steps and try to send a log

**Comment by DennisAlund** [comment]
Not sure if this is related to this plugin. The `nw_protocol_instance_access_flow_state` reference is not from any of the plugin code. 

And Googling for it (https://www.google.com/search?q=nw_protocol_instance_access_flow_state), it seems to appear in logs from other Firebase SDK related issues... could you try to narrow the issue down to how it is affected by this plugin 🙏  

I will close since it seems to not be related to the plugin. Please re-open if you have a case that can link it to the plugin.
