### ISSUE TITLE
Undefined symbol: _FBSDKAppEventLastName

### ISSUE THREAD

**Issue by simo9900** [oddbit/flutter_facebook_app_events#127]
I have this error when compiling ios

![Capture](https://user-images.githubusercontent.com/22013745/129460862-b4d43d64-8b64-4df4-9f7e-13a2745db6e8.JPG)

Thanks for help

**Comment by iMinger** [comment]
mee too!!!

**Comment by suryaoddbit** [comment]
Sorry for having kept you waiting. We're work on it.

**Comment by shtreb** [comment]
When should we expect a fix?

**Comment by DennisAlund** [comment]
Please see suggested fix in PR #130 ... we couldn't narrow down the problem and went with a workaround. We'd be happy to re-implement the deprecated function support during the grace period if there is a community member that manages to keep the deprecated methods without compilation errors.

But otherwise, it will be a short period of time where the deprecated parts are just removed slightly faster than they are in official SDK.
