### ISSUE TITLE
`setUserData` and `updateUserProperties` is deprecated, how can set custom user properties going forward?

### ISSUE THREAD

**Issue by Aadiyaara** [oddbit/flutter_facebook_app_events#136]

**Comment by DennisAlund** [comment]
Use issues for technical problems with the plugin.

We are only implementing a plugin for Flutter that is enabling support for existing Facebook SDK. We are not the ones deprecating the functionality from Facebook's SDK. Please write to Facebook and ask 🙏  because I don't have a good answer.

For future reference. Use StackOverflow for discussions or request for help and support.
