### ISSUE TITLE
[Bug]: App events not received on ios14 devices

### ISSUE THREAD

**Issue by opringle** [oddbit/flutter_facebook_app_events#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Install the example app on an ios14+ device (not simulator)
Log into the facebook app on this device
Open event testing UI
Start using the example app
No app events are received

### Expected Behavior

App events are shown in the testing UI within 20 minutes.

### Steps To Reproduce

1. Install the example app on an ios14+ device (not simulator)
2. Log into the facebook app on this device
3. Open event testing UI
4. Start using the example app
5. No app events are received

### Platform

iOS

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by pwnywiz** [comment]
same here on my app after having applied all the required configurations

**Comment by kevinzDzul** [comment]
The same thing happened to me, I couldn't track the events of the device in ios. I solved it in the following way.
1.- activate in the facebook application "allow tracking"
in iOS setting (iOS settings > Facebook > Allow Tracking).

![File](https://user-images.githubusercontent.com/88689412/151715444-d2a0d5d7-de4d-4b30-8bbc-a367f51bff4c.jpg)


2.- restart the facebook application and leave it in the background.

3.- restart your application.

after this I was able to see my application events.
In my case I could only receive the fb_mobile_install event because it is the only one that recognizes fb events by default, but if you configured the click event you should already be able to see it in the console.


```
facebookAppEvents.logEvent(
    name: 'Test Link Clicked',
    parameters: {'url':  'www.google.com'},
);
```
In the same way, check that you have added your platform to the configuration in the IOS configuration panel.

<img width="785" alt="Captura de Pantalla 2022-01-30 a la(s) 2 01 36 p m" src="https://user-images.githubusercontent.com/88689412/151715566-74b9f2f2-5ee2-46be-9ea0-b83e649effb0.png">

As a comment in my case I had to add this library to give the application permission to track the user's information by the new apple policies.

[tracking transparency](https://pub.dev/packages/app_tracking_transparency)

I share my validation code in flutter.

```dart
import 'dart:io' show Platform;
import 'package:app_tracking_transparency/app_tracking_transparency.dart';
import 'package:facebook_app_events/facebook_app_events.dart';

class FacebookTracking {
  FacebookTracking();

  Future<void> _facebookTracking() async {
    FacebookAppEvents facebookAppEvents = FacebookAppEvents();
    await facebookAppEvents.setAdvertiserTracking(enabled: true);
    await facebookAppEvents.setAutoLogAppEventsEnabled(true);
  }

  Future<void> _iosValidation() async {
    //Request tracking to user in ios devices.
    TrackingStatus status =
        await AppTrackingTransparency.requestTrackingAuthorization();
    if (status == TrackingStatus.authorized) {
      await _facebookTracking();
    }
  }

  Future<void> _androidValidation() async {
    await _facebookTracking();
  }

  Future<void> init() async {
    if (Platform.isAndroid) {
      await _androidValidation();
    }
    if (Platform.isIOS) {
      await _iosValidation();
    }
  }
}

```

I hope this helps you, it worked for me but each problem can be different in each case.

**Comment by ferysyukur** [comment]
> The same thing happened to me, I couldn't track the events of the device in ios. I solved it in the following way. 1.- activate in the facebook application "allow tracking" in iOS setting (iOS settings > Facebook > Allow Tracking).
> 
> ![File](https://user-images.githubusercontent.com/88689412/151715444-d2a0d5d7-de4d-4b30-8bbc-a367f51bff4c.jpg)
> 
> 2.- restart the facebook application and leave it in the background.
> 
> 3.- restart your application.
> 
> after this I was able to see my application events. In my case I could only receive the fb_mobile_install event because it is the only one that recognizes fb events by default, but if you configured the click event you should already be able to see it in the console.
> 
> ```
> facebookAppEvents.logEvent(
>     name: 'Test Link Clicked',
>     parameters: {'url':  'www.google.com'},
> );
> ```
> 
> In the same way, check that you have added your platform to the configuration in the IOS configuration panel.
> 
> <img alt="Captura de Pantalla 2022-01-30 a la(s) 2 01 36 p m" width="785" src="https://user-images.githubusercontent.com/88689412/151715566-74b9f2f2-5ee2-46be-9ea0-b83e649effb0.png">
> 
> As a comment in my case I had to add this library to give the application permission to track the user's information by the new apple policies.
> 
> [tracking transparency](https://pub.dev/packages/app_tracking_transparency)
> 
> I share my validation code in flutter.
> 
> ```dart
> import 'dart:io' show Platform;
> import 'package:app_tracking_transparency/app_tracking_transparency.dart';
> import 'package:facebook_app_events/facebook_app_events.dart';
> 
> class FacebookTracking {
>   FacebookTracking();
> 
>   Future<void> _facebookTracking() async {
>     FacebookAppEvents facebookAppEvents = FacebookAppEvents();
>     await facebookAppEvents.setAdvertiserTracking(enabled: true);
>     await facebookAppEvents.setAutoLogAppEventsEnabled(true);
>   }
> 
>   Future<void> _iosValidation() async {
>     //Request tracking to user in ios devices.
>     TrackingStatus status =
>         await AppTrackingTransparency.requestTrackingAuthorization();
>     if (status == TrackingStatus.authorized) {
>       await _facebookTracking();
>     }
>   }
> 
>   Future<void> _androidValidation() async {
>     await _facebookTracking();
>   }
> 
>   Future<void> init() async {
>     if (Platform.isAndroid) {
>       await _androidValidation();
>     }
>     if (Platform.isIOS) {
>       await _iosValidation();
>     }
>   }
> }
> ```
> 
> I hope this helps you, it worked for me but each problem can be different in each case.

hi @opringle and @pwnywiz. Did you have try this way ? Let me know if you still have issue like this.

**Comment by DennisAlund** [comment]
@opringle I saw you ticked that you had searched the repository for similar issues. There is a discussion on this topic. Let's proceed the discussion here: https://github.com/oddbit/flutter_facebook_app_events/discussions/122 

I'll close this and please consolidate the conversations in a single thread and we'll open this issue if it has distinct characteristics that are not related to the other "iOS14 no events logged".

**Comment by pwnywiz** [comment]
Thanks a lot for the info. After allowing tracking on the facebook app, i finally managed to see the events in the test events panel. However, I still cant get SKAdNetwork to recognise my events. Im opening up the app from the facebook notification after pressing 'Start setting up events' and it never receives any event. Has anyone got this part to work? Thanks

**Comment by DennisAlund** [comment]
Thanks for engagement @pwnywiz it seems like your question is more of a discussion character, rather than a bug on the technical implementation of the plugin. See if you can find a good place to discuss that in the discussions section https://github.com/oddbit/flutter_facebook_app_events/discussions or on Stack Overflow.

**Comment by pwnywiz** [comment]
sure, ill move the discussion over the Discussions section. Thanks :)
