### ISSUE TITLE
Aggregated Event Measurement

### ISSUE THREAD

**Issue by ldemyanenko** [oddbit/flutter_facebook_app_events#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Looks like Facebook implemented new feature for [Event Measurement optimisation ](https://www.facebook.com/business/help/721422165168355?id=1877298665783613)
It is an IOS side only improvement. Is there a way to use [Aggregated Event Measurement](https://developers.facebook.com/docs/app-events/guides/aggregated-event-measurement) with this plugin? 

### Expected Behavior

Would be great to if this functionality would be available. 

### Platform

iOS

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.3.1 21E258 darwin-arm, locale
    en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by ibrahimdevs** [comment]
I have the exact same problem.
This pull request seems fixing it. https://github.com/oddbit/flutter_facebook_app_events/pull/236
@wwnOddbit could you check it please? You just merged "Bumping up FBSDK version to v14.1.0", so after this issue is completed, it is time to new version. Thank you for this library, it saves tons of time for us.

There is detailed explanation docs: https://developers.facebook.com/docs/app-events/guides/aggregated-event-measurement/
