### ISSUE TITLE
Facebook codeless events

### ISSUE THREAD

**Issue by LiveRock** [oddbit/flutter_facebook_app_events#41]
Does the package support Facebook codeless events?
I tried but couldn't see any FB event firing

**Comment by DennisAlund** [comment]
Thank you for showing an active interest in engaging with the further improvement of the plugin. But in context of your last issue report https://github.com/oddbit/flutter_facebook_app_events/issues/38#issuecomment-660421326 please try to be more structured before asking for help in an issue here in the repository. 


1. Read the documentation that encourages to follow full setup instructions on Facebook Developer site
1. You can discuss usage on Stack Overflow 
1. 👉   [Use the issue template](https://github.com/oddbit/flutter_facebook_app_events/issues/new?assignees=&labels=&template=bug_report.md&title=) 👈   if you narrowed it down to an code-related bug
1. Alternatively, create a pull request with updates to the documentation if something is missing or can be improved.

But yes, it should work, since it's something that should be enabled as part of the respective native configuration.
https://developers.facebook.com/docs/app-events/codeless-app-events#android-integration
