### ISSUE TITLE
Readme needs to be a bit clearer

### ISSUE THREAD

**Issue by rmargolinross** [oddbit/flutter_facebook_app_events#59]
This plugin is awesome but the instructions for setup could be a bit more clear. I know it mentions to follow the setup instructions on facebook's pages, but it would be nice to know which steps to skip and which to focus on or maybe not have to go to facebook's instructions at all.

I am curious if this plugin provides the sdk already for you so you don't have to follow the steps to install it on the individual platforms.

**Comment by DennisAlund** [comment]
I appreciate your feedback and please provide a pull request with the changes that you would like to see. Because "not clear enough" is individually subjective and will be different from each reader. What we can do is to provide best possible documentation from the author's own assumptions about reader's understanding. And for me it is good enough.

As for duplicating the documentation from Facebook's official page it will not be done. It only adds the value of saving the reader from having to read and adds load on the writer to maintain. I suggest instead that you spend a few minutes reading the official documentation on Facebook's offical page.

Binaries are not bundled with this plugin and will not be. It is not how plugins are intended to be structured.
