### ISSUE TITLE
iOS initialization on SDK 9.0.0

### ISSUE THREAD

**Issue by mikicleverppc** [oddbit/flutter_facebook_app_events#89]
It seems that the `autoInitEnabled` has been removed on SDK version 9.0.0, as you can see on [changelog](https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md#removed-1)

After upgrading to 0.11.0 version I'm getting this error after logEvent():

`FBSDKLog: FBSDKGraphRequestConnection cannot be started before Facebook SDK initialized.`

## Expected Behavior
SDK should initialize and log events.

## Current Behavior
SDK is not being initialized

## Possible Solution
The solution may be on [iOS Doc Step 6](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios)

## Your Environment
iOS 14.5 and library version 0.11.0

**Comment by jun-exposure** [comment]
Hi, have you found a solution?

**Comment by andrewjallenuoft** [comment]
I can also confirm that the most recent version works on Android but not iOS.

**Comment by jun-exposure** [comment]
I added the code as described in FB's documentation step 6, including registering the Flutter plugin as an app delegate. Compiles and installs fine, but still no install events. Going to play around with it some more.

**Comment by jun-exposure** [comment]
@Maegondo thanks for the information re. 0.10.0. I can confirm it works with 0.10.0. I'm going to try to get initialization working with 0.11.0 and FB SDK 9.

**Comment by DennisAlund** [comment]
Thank you @jun-exposure please let me know if you find a solution. This sounds terrible and urgent. I'm currently under a bit of heavy workload elsewhere myself, so I really appreciate the support 🤗

**Comment by jun-exposure** [comment]
Good news. I have a fix. FB's documentation is a bit misleading as it makes it look like calling their didFinishLaunchingWithOptions would initialize it implicitly. It finally occurred to me that they probably didn't update their documentation. Changing to an explicit call to initializeSDK did the trick. That's why it took me a little longer to get it working for what seems an easy change.

@DennisAlund I'll create the PR from my personal github account.

**Comment by DennisAlund** [comment]
Solved in version: 0.11.2
